Change dataset details page PID text to a input field with copy button
SciCatProject/frontend pull request #1051
Opened 2023-04-18 19:55 UTC by TheMeinerLP

## Description

On the detail page of a dataset is a PID. Normaly the user needs to select manually the PID. This PR adds a input field with simple copy option. 

## Motivation

To deliver more easy a dataset PID add a UX improvement.

## Fixes:

* Nothing

## Changes:

* UX improvement

## Tests included/Docs Updated?

- [ ] Included for each change/fix?
- [ ] Passing? (Merge will not be approved unless this is checked) 
- [ ] Docs updated?
- [ ] New packages used/requires npm install? 
- [X] Toggle added for new features?
- [ ] Requires update of SciCat backend API?

2023-04-19 12:04 UTC, nitrosx requested changes
Check the scicat token copy under the user settings page. 
We should implement it as it is done there

2023-04-19 12:04 UTC, nitrosx commented on src/app/datasets/dataset-detail/dataset-detail.component.html
> +                <mat-form-field class="full-width">
Instead of creating a full functional text box, can we just add the copy button, like is done under user settings with the [scicat token](https://github.com/SciCatProject/frontend/blob/757d07978013d7161aa54c6f6b2513f728c427c0/src/app/users/user-settings/user-settings.component.html#L52)

2023-04-19 12:22 UTC, Junjiequan commented on src/app/datasets/dataset-detail/dataset-detail.component.html
> +                <mat-form-field class="full-width">
From the best practice point of view, especially if you are an accessibility enthusiast, I wouldn't recommend to use onClick in a span to make it a button.
But in our case, I think it is completely fine to follow the pattern what we already have for consistency, and you can add an aria attribute if you want to.

2023-04-19 13:03 UTC, TheMeinerLP commented on src/app/datasets/dataset-detail/dataset-detail.component.html
> +                <mat-form-field class="full-width">
Okay i will check that from the settings page and improve the current code

2023-04-21 07:21 UTC, minottic commented
after the changes, I would add a test, similar to this: https://github.com/SciCatProject/frontend/blob/757d07978013d7161aa54c6f6b2513f728c427c0/src/app/users/user-settings/user-settings.component.spec.ts#L72-L91

2023-04-24 13:48 UTC, nitrosx approved these changes

2023-04-24 13:49 UTC, merged