Fix: Changed profile.username to profile.displayName for header username display
SciCatProject/frontend pull request #1388
Opened 2024-01-30 13:53 UTC by Junjiequan

## Description

This PR adapts to the https://github.com/SciCatProject/scicat-backend-next/pull/1041
In the above backend PR we have changed `profile.username` to store `oidc.sub` by default, which in some cases might return string of numbers instead of user's name. So the change of displaying `profile.username` to` profile.displayName` on the header section is required.

## Tests included/Docs Updated?

- [ ] Included for each change/fix?
- [ ] Passing? (Merge will not be approved unless this is checked) 
- [ ] Docs updated?
- [ ] New packages used/requires npm install? 
- [ ] Toggle added for new features?
- [ ] Requires update of SciCat backend API?

2024-01-30 15:07 UTC, bpedersen2 requested changes
Good idea, could get some simplification. 

Actually the `replace(' ms-ad',...`) is probably wrong at all places,  as e.g. the `oidc.` prefix would need the same handling. 

Users without a profile should be limited to the system accounts, if I am not mistaken.

2024-01-30 15:07 UTC, bpedersen2 commented on src/app/state-management/selectors/user.selectors.ts
> +      return profile.displayName.replace("ms-ad.", "");
the replace is probably not needed here then.  The backend prependes a marker for the auth source to the username, but  should not do that for the displayName.

2024-01-30 15:19 UTC, bpedersen2 commented on src/app/state-management/selectors/user.selectors.ts
> +      return profile.displayName.replace("ms-ad.", "");
I  checked and all user types do implement the user profile (local, oidc, ldap) . jwt auth relies on the other strategies for initial login/account creation, so we proably can rely on the profile being there (or adopt the BE to ensure that),

2024-02-19 11:08 UTC, nitrosx requested changes

2024-02-19 11:08 UTC, nitrosx commented on src/app/state-management/selectors/user.selectors.ts
> +      return profile.displayName.replace("ms-ad.", "");
@bpedersen2 hopefully I understood your comment above correctly. 
To clarify further: user profile is created for all accounts, no matter which auth strategy they use. It is safe to assume that profile is always present.
I agree with you that the displayName should not be stored in the db with a prefix.
We should display it as it is saved in the database.

2024-02-26 16:08 UTC, nitrosx approved these changes

2024-03-05 15:17 UTC, bpedersen2 approved these changes

2024-03-05 19:03 UTC, merged