fixes #1553
SciCatProject/frontend pull request #1554
Opened 2024-08-14 14:52 UTC by belfhi

as described in the issue, the user does not need to be `root`, even for _nginx_.
This PR sets the `nginx.conf` the way the official [docs](https://hub.docker.com/_/nginx) describe what is needed to run as a rootless user.

2024-08-19 06:40 UTC, bpedersen2 requested changes
Generally a good idea.

But as it breaks existing installations, it needs prominent mentions in changelog and readme, and probabaly an announcement in the scicat mailinglist at least.

2024-08-19 06:40 UTC, bpedersen2 commented on scripts/nginx.conf
> +    client_body_temp_path /tmp/client_temp;
I would prefer to keep the original locations ( var/cache/nginx/... ) and instead fix permissions  in the image build.

2024-08-22 04:33 UTC, belfhi commented on scripts/nginx.conf
> +    client_body_temp_path /tmp/client_temp;
That's also an option. It was more along the line of "just log to stdout / stderr if it's running in a container".

2024-11-29 09:10 UTC, bpedersen2 commented on scripts/nginx.conf
> +    client_body_temp_path /tmp/client_temp;
See also #1657

2025-08-06 13:59 UTC, closed without merging

2025-08-06 13:59 UTC, Junjiequan commented
Ths issue is addressed in this PR #1657