Load/Upload user filters and conditions from/to be
SciCatProject/frontend pull request #1563
Opened 2024-08-26 17:39 UTC by Ingvord

- [x] Load default user settings from the server 
- [x] Load/Upload current user filters and conditions from/to BE

Resolves https://github.com/SciCatProject/scicat-backend-next/issues/616

2024-08-29 09:06 UTC, Junjiequan requested changes

2024-08-29 09:06 UTC, Junjiequan commented on src/app/shared/services/user-settings.service.ts
> +}
Please move this to `/shared/sdk/services/custom/User.ts`

2024-08-29 10:17 UTC, Ingvord commented on src/app/shared/services/user-settings.service.ts
> +}
Why?

2024-08-29 15:36 UTC, Junjiequan commented on src/app/shared/services/user-settings.service.ts
> +}
Are you asking why we shouldn't have specific class for this endpint or?

2024-08-29 15:42 UTC, Ingvord commented on src/app/shared/services/user-settings.service.ts
> +}
No, sorry, I am asking why you want to move it. It seems the destination is auto-generated.

2024-08-29 16:02 UTC, Junjiequan commented on src/app/shared/services/user-settings.service.ts
> +}
The SDK was generated long ago but no longer maintained. 
We directly modify the corresponding files in the `SDK/services/custom` until we replace it with new SDK.

2024-08-29 16:06 UTC, Ingvord commented on src/app/shared/services/user-settings.service.ts
> +}
Sounds scary :fearful:

2024-08-30 06:56 UTC, Junjiequan commented on src/app/shared/services/user-settings.service.ts
> +}
Yes, it is bad. we need to replace the old one with new SDK asap.

2024-08-30 08:45 UTC, Ingvord commented on src/app/shared/services/user-settings.service.ts
> +}
Well, not only we need to upgrade it asap, but I would strongly recommend NOT to keep auto-generated code in the repo. Way better is to include it via dependency, I believe there is some progress already in that direction, right?! Also this will help to clear which API version is being used

2024-09-02 18:42 UTC, Junjiequan commented on src/app/shared/services/user-settings.service.ts
> +}
I completely agree with your point. I’ll make sure to pass this feedback along when I next catch up with the colleague who managed this, although they left quite a few years ago. :) It’s definitely something we should keep in mind as we move forward with upgrading and managing dependencies.

2024-09-24 08:35 UTC, nitrosx requested changes

2024-09-24 08:35 UTC, nitrosx commented on src/app/shared/sdk/models/Dataset.ts
> +  instrumentIds?: string | string[];
This should not be necessary. 
Datasets output DTO should be the same as before

2024-09-24 08:35 UTC, nitrosx commented on src/app/datasets/dataset-detail/dataset-detail.component.html
The field's names should be singular as the dataset output dto did not change

2024-09-24 08:35 UTC, nitrosx commented on src/app/datasets/dataset-details-dashboard/dataset-details-dashboard.component.ts
The field's names should be singular as the dataset output dto did not change

2024-10-03 10:10 UTC, nitrosx approved these changes

2024-10-03 10:10 UTC, merged