Link raw derived datasets
SciCatProject/frontend pull request #976
Opened 2022-06-16 14:47 UTC by henrikjohansson712

## Description

Add a new tab to dataset details view, that contains a table showing all related datasets for the current datasets.

## Motivation

See issue #932

## Fixes:

* #932

## Changes:

* Add new related datasets component
* Set up lazy loading of new component

## Tests included/Docs Updated?

- [x] Included for each change/fix?
- [x] Passing? (Merge will not be approved unless this is checked) 
- [ ] Docs updated?
- [ ] New packages used/requires npm install? 
- [ ] Toggle added for new features?
- [ ] Requires update of SciCat backend API?

2022-06-23 11:53 UTC, henrikjohansson712 commented on src/app/datasets/dataset-detail/dataset-detail.component.ts
> +          this.store.dispatch(fetchDatasetAction({ pid: id }));
Without this, if you click on a related dataset to go to the details page for that, you will still see the data from the previous dataset. Couldn't find any other way to get around it.

2022-06-23 11:54 UTC, henrikjohansson712 commented on src/app/datasets/related-datasets/related-datasets.component.ts
> +    this.store.dispatch(fetchRelatedDatasetsAction());
The problem here is the same as the one above. Without you still see the related datasets of the previous dataset.

2022-06-23 12:08 UTC, henrikjohansson712 commented on src/app/state-management/reducers/datasets.reducer.ts
> +
Added these clear actions to the new component now because I realized that it would still show the old sample and proposal when you go to a related dataset. Now I have the problem that they are not fetched for the new dataset, because those actions are dispatched in the dataset-details-dashboard-component.

2022-06-23 12:12 UTC, henrikjohansson712 commented
@nguyenlinhlinh I can't seem to get this component to play nicely with the lazy loading. If you have any suggestions on how to fix the things above, please let me know.

The problem seems to be that all the actions to fetch and clear state data are done in the dataset-details-component, but since you never actually leave that component when switching between the tabs, or go to related dataset, the state doesn't change.

2022-06-23 14:01 UTC, nguyenlinhlinh commented
@henrikjohansson712 I will take a look into it and let you know if I figure it out.

2022-06-30 11:47 UTC, henrikjohansson712 commented
@nguyenlinhlinh I've added a service to help with reloading the data in the view. Let me know what you think.

2022-07-11 08:22 UTC, nguyenlinhlinh requested changes

2022-07-11 08:22 UTC, nguyenlinhlinh commented on src/app/datasets/dataset-details-dashboard/dataset-details-dashboard.component.ts
> +    this.lazyChildService.childChanges().subscribe((tabName) => {
In this function I would dispatch these actions 
``` 
    this.store.dispatch(clearCurrentDatasetStateAction());
    this.store.dispatch(clearCurrentProposalStateAction());
    this.store.dispatch(clearCurrentSampleStateAction());
```
and 
Set all tabs in `fetchDataActions` to false. Because it is a new dataset so data for all tabs should be loaded

2022-07-11 08:22 UTC, nguyenlinhlinh commented on src/app/datasets/related-datasets/related-datasets.component.ts
> +    this.store.dispatch(clearCurrentSampleStateAction());
We should move line 111 - 113 to parent component. I think we should avoid changing data of other tabs in child components because the data will be out of sync and it is easy to get bugs because of that.

2022-07-11 09:54 UTC, henrikjohansson712 commented on src/app/datasets/dataset-details-dashboard/dataset-details-dashboard.component.ts
> +    this.lazyChildService.childChanges().subscribe((tabName) => {
Done!

2022-07-11 09:54 UTC, henrikjohansson712 commented on src/app/datasets/related-datasets/related-datasets.component.ts
> +    this.store.dispatch(clearCurrentSampleStateAction());
Done!

2022-07-11 11:04 UTC, nguyenlinhlinh commented
@henrikjohansson712 Thank you for making the changes. Sorry, I tried the user interface and the data still doesn't update properly for some tabs. I think we need to also clear the attachment, (maybe also the reducer and logbook, I am not sure) and originblocks (for datafiles). Btw, what day is your last day?

2022-07-11 12:18 UTC, henrikjohansson712 commented
@nguyenlinhlinh My last day is Friday this week. Not sure how much time I'll have to work on this PR.

2022-07-11 15:06 UTC, nguyenlinhlinh commented
@henrikjohansson712 I see. If you dont have time to work on it I can pick it up after you have left.

2022-07-19 11:45 UTC, nguyenlinhlinh approved these changes

2022-08-15 14:38 UTC, nitrosx commented
Tested and working

2022-08-15 14:38 UTC, merged